batch_size: 2
natq_json_file: 'natq.json'
cache_folder: 'cached_natq'
model_name: 'bert-base-uncased'
loss_type: 'classification'
optimizer_type: 'adam'
max_question_len: 30
max_paragraph_len: 512
embedding_dim: 768
patience: 5
gradient_clipping: 0
