batch_size: 2
train_file: 'train.json'
dev_file: 'dev.json'
cache_folder: 'cached_natq'
model_name: 'bert-base-uncased'
loss_type: 'classification'
freeze_bert: true
optimizer_type: 'adamw'
max_question_len: 30
max_paragraph_len: 512
embedding_dim: 768
patience: 5
gradient_clipping: 0
pooling_type: 'avg'
precision: 32
